import React, { useState, useEffect, useMemo } from 'react';
import { Plus, ChevronRight, ChevronDown, Edit2, Trash2, FolderPlus } from 'lucide-react';
import { fetchWBS, addWBSItem, updateWBSItem, deleteWBSItem } from '../api';
import EditModal from './EditModal';

// Helper to build tree
const buildTree = (items) => {
    const map = {};
    const roots = [];

    // Initialize map
    items.forEach(item => {
        map[item.id] = { ...item, children: [] };
    });

    // Build hierarchy
    items.forEach(item => {
        if (item.parentId && map[item.parentId]) {
            map[item.parentId].children.push(map[item.id]);
        } else {
            roots.push(map[item.id]);
        }
    });

    return roots;
};

// Flatten tree for table display, handling expanded state
const flattenTree = (nodes, expandedIds, level = 0) => {
    let result = [];
    nodes.forEach(node => {
        result.push({ ...node, level });
        if (expandedIds.has(node.id) && node.children.length > 0) {
            result = result.concat(flattenTree(node.children, expandedIds, level + 1));
        }
    });
    return result;
};

export default function WBSGrid() {
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(true);
    const [expandedIds, setExpandedIds] = useState(new Set());

    // Modal State
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingItem, setEditingItem] = useState(null); // If null, adding new. If set, editing.
    const [addingParentId, setAddingParentId] = useState(null); // For "Add Subtask"

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        try {
            setLoading(true);
            const data = await fetchWBS();
            setItems(data);
            // Auto expand all for now or keep simple? Let's auto expand roots
            // const ids = new Set(data.map(d => d.id));
            // setExpandedIds(ids);
        } catch (err) {
            console.error(err);
            alert('Failed to load WBS data');
        } finally {
            setLoading(false);
        }
    };

    const toggleExpand = (id) => {
        setExpandedIds(prev => {
            const newSet = new Set(prev);
            if (newSet.has(id)) newSet.delete(id);
            else newSet.add(id);
            return newSet;
        });
    };

    const handleAddRoot = () => {
        setEditingItem(null);
        setAddingParentId("");
        setIsModalOpen(true);
    };

    const handleAddSubtask = (parentId) => {
        setEditingItem(null);
        setAddingParentId(parentId);
        setIsModalOpen(true);
    };

    const handleEdit = (item) => {
        setEditingItem(item);
        setAddingParentId(null);
        setIsModalOpen(true);
    };

    const handleDelete = async (id) => {
        if (window.confirm('Are you sure you want to delete this task?')) {
            try {
                await deleteWBSItem(id);
                setItems(prev => prev.filter(i => i.id !== id));
            } catch (err) {
                alert('Failed to delete item');
            }
        }
    };

    const handleSave = async (data) => {
        try {
            if (editingItem) {
                // Update
                const updated = await updateWBSItem(data);
                if (updated.status === 'success') {
                    // Refetch or update local
                    setItems(prev => prev.map(i => i.id === data.id ? data : i));
                }
            } else {
                // Add
                const newItem = { ...data, parentId: addingParentId || "" };
                const result = await addWBSItem(newItem);
                if (result.status === 'success') {
                    // Need data with ID potentially if generated by backend, but mock gen has it
                    setItems(prev => [...prev, result.data]);
                    // Auto expand parent
                    if (addingParentId) {
                        setExpandedIds(prev => new Set(prev).add(addingParentId));
                    }
                }
            }
            setIsModalOpen(false);
        } catch (err) {
            console.error(err);
            alert('Failed to save item');
        }
    };

    // Memoize tree & flat list
    const flatItems = useMemo(() => {
        const tree = buildTree(items);
        return flattenTree(tree, expandedIds);
    }, [items, expandedIds]);

    if (loading) return <div className="p-8 text-center text-gray-400">Loading WBS...</div>;

    return (
        <div className="w-full h-full flex flex-col">
            <div className="p-4 flex justify-between items-center glass-panel mb-4 mx-4 mt-4">
                <h1 className="text-2xl font-bold text-white tracking-tight">Project WBS</h1>
                <button onClick={handleAddRoot} className="btn btn-primary">
                    <Plus size={18} /> New Root Task
                </button>
            </div>

            <div className="flex-1 overflow-auto px-4 pb-4">
                <div className="glass-panel w-full overflow-hidden">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-slate-800/50 text-gray-400 text-sm border-b border-gray-700">
                                <th className="p-4 w-[400px]">Task Name</th>
                                <th className="p-4">Duration</th>
                                <th className="p-4">Start</th>
                                <th className="p-4">End</th>
                                <th className="p-4">Assigned To</th>
                                <th className="p-4">Status</th>
                                <th className="p-4 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {flatItems.length === 0 ? (
                                <tr>
                                    <td colSpan={7} className="p-8 text-center text-gray-500">
                                        No tasks yet. Create one to get started.
                                    </td>
                                </tr>
                            ) : (
                                flatItems.map(item => (
                                    <tr key={item.id} className="hover:bg-slate-700/30 transition-colors border-b border-slate-700/50 last:border-0 group">
                                        <td className="p-3">
                                            <div style={{ paddingLeft: `${item.level * 24}px` }} className="flex items-center gap-2">
                                                {item.children && item.children.length > 0 ? (
                                                    <button onClick={() => toggleExpand(item.id)} className="text-gray-400 hover:text-white transition-colors">
                                                        {expandedIds.has(item.id) ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                                                    </button>
                                                ) : (
                                                    <span className="w-4" /> // Spacer
                                                )}
                                                <span className="font-medium text-gray-200">{item.name}</span>
                                            </div>
                                        </td>
                                        <td className="p-3 text-gray-400 text-sm">{item.duration}</td>
                                        <td className="p-3 text-gray-400 text-sm">{item.startDate}</td>
                                        <td className="p-3 text-gray-400 text-sm">{item.endDate}</td>
                                        <td className="p-3">
                                            {item.assignedTo && <span className="bg-slate-800 text-xs px-2 py-1 rounded-full text-blue-300 border border-slate-700">{item.assignedTo}</span>}
                                        </td>
                                        <td className="p-3">
                                            <StatusBadge status={item.status} />
                                        </td>
                                        <td className="p-3 text-right">
                                            <div className="flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <button onClick={() => handleAddSubtask(item.id)} className="p-1.5 text-blue-400 hover:bg-blue-400/10 rounded" title="Add Subtask">
                                                    <FolderPlus size={16} />
                                                </button>
                                                <button onClick={() => handleEdit(item)} className="p-1.5 text-gray-400 hover:bg-gray-700 rounded" title="Edit">
                                                    <Edit2 size={16} />
                                                </button>
                                                <button onClick={() => handleDelete(item.id)} className="p-1.5 text-red-400 hover:bg-red-400/10 rounded" title="Delete">
                                                    <Trash2 size={16} />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            <EditModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                item={editingItem}
                onSave={handleSave}
            />
        </div>
    );
}

function StatusBadge({ status }) {
    let color = "bg-gray-800 text-gray-300 border-gray-700";
    if (status === 'Done') color = "bg-green-500/10 text-green-400 border-green-500/20";
    else if (status === 'In Progress') color = "bg-blue-500/10 text-blue-400 border-blue-500/20";
    else if (status === 'Blocked') color = "bg-red-500/10 text-red-400 border-red-500/20";

    return (
        <span className={`text-xs px-2 py-1 rounded-full border ${color}`}>
            {status}
        </span>
    );
}
